spring:
  application:
    name: remember
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/remember_app?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
#  jackson:
#    property-naming-strategy: SNAKE_CASE

remember:
  security:
    rsa-private-key: 'MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDudNO3Iv3HpwBOy8bM9tNUUvAurQH0+HmNEGa8rYSX5drlSeANP3yZx/SGy2EGVism/wQcZiEZwBkAliWfjecQqhXyI/MYlKtayiRbvAMJj0c4LikqWoOiidr95Pbqg6M6sE4Mu06+K1LiKQfraG05kD6GXi4d+7/r/b55BTwVNeJOmylzVslRnSjWxbcfZiACKZzEDlFiAINKMoy33+6+iNWDEtjFpzLxR7XA7w1ZaFxpQG1hc7x0/0XRkl4+sqy95MTMMU2EWmvPD0NR/58gOh8GNmi+ktysKWVVzVEjWhbUSndd+4aN67w25EmK3AZzhPBv9u29spSPe/xjXJ7hAgMBAAECggEAAVNZbzwoPaXIjXnevSgF9zncF3N6Hlf4jd6FFEKBZKgQIsaHZO7jT0GvDkYPYCA/3Du+VKSDajxo5OLVXTWYakaxfgna6H7AgmTNo0vphNbDq/usR/t1MDupKuLM2nNkGd6rrYwVccyMWzokYSoHjkTUMCb2qgY4bU1iM5OrVkz69SEPUB5q5STiCXvglg8La7qtCoy2EuyilrF6uzSDaEHB0urK+O43PyLTUtXgCNN2ENCtqKz+XlOC0wEJNhl1ULDaZtlXNNARZK78lAPZ3bqJpHXym9c7FH1pUg0ol3KmhOjPLvcsSWlKukgt7vc9A2snH8aDHEb1A7PzGLHitQKBgQD51qHIXY0GzjWwJFbxlnyuUWv2bQ3cZLv4X3dnt7alRwDeiLvQpBeIigUpZ6IS0A0oe19aN11gaVJeD2cEX37H31gnL2KWHLCpXLMvJutU2z52azLudTNOtkSmbk7kMnIcCb4hUj984hSUgH0krJZtpx/2kJwg9Bvf7iJfI5sW9QKBgQD0VlV4cvTjq+OEYnz6B417r9HP8LxPmh5pz5rmSFcIVGhDMjiX2NpALXBziqy1lUeaoH0WVB2bL+w9wBv95tz5BEZu/lWQ+eczBkHLpBCIs5JSmqYsdpudHR+6Y1rwt+tw37+97JD4346ujKJEtoAItv8iIEGouPpn+fAHDQZ8vQKBgGnUaimGv0NfvExFyHKDrYLlyJbVMSbnoNwgDGNp5btzLUIWp4BE0hcrZ+5XEMdpS/mW8Rg1FZ/OXW6slZW7oeemix/mKZuuwYKsWtahZNRIHthopmVuTfKMsN3TIiX13HJWCizxOyV6Wv9gwiHz3bDLN3XpYclvvhMIO5UTbxG1AoGAMIuarbTBXR7AtIPQ6uhnPuTe3d6pu3MWidVapFhJGnmSwY8P2XOXYVrl1b7+s5E2Sc2LLM2HmFa8LESoCxk8XClySQk1PPm56tRabDhrpI1xDAJ386uZHW006ZZl8h/IooOCGB0RbLEWKy3764ULCTA6nrAj+37NGa15+BypZk0CgYEAh5MLbm02BmL4Z1ozvpKt+hB6E69doiAO/g6EemvBQyU7c2yIgMV/PoVQEket1ZUQVKCXR8gSUENI/k//bxnLVwpcxvyl7hZOEpevzwzUeR2rTOfCR2/Qx4zMpJO2MMUcYen+hyem+Fr7Dwf8EWBjQovK8NVRnSh9nDre8wcW3Rk='
    jwt-secret: 'R9a#k7P!m2N$zL5vW8xY4uQ1tB0cE3gH6jI9sK2fV5dQ8wZ1'
    jwt-expire: 86400000

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml